#!/usr/bin/env python2

import argparse
from server_vm import ServerVM

def run():
    p = argparse.ArgumentParser()
    p.add_argument("vm_name_tag")
    p.add_argument("git_reference")
    options = p.parse_args()
    print "VM name tag: ", options.vm_name_tag
    print "Reference: ", options.git_reference

    vm = ServerVM(options.vm_name_tag, options.git_reference)
    vm.run()
    print vm.ssh_example()

if __name__ == '__main__':
    run()
